language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
install:
  - pip install -r .travis-requirements.txt
  - pip install -e . --use-mirrors
script:
  - coverage run -m behave --no-capture
after_success:
  - coverage report -m
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
