os:
  - 'linux'
sudo: false
language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r ./requirements/ci.txt
  - pip install -e .
script:
  - behave --no-capture
  - nosetests --nocapture --with-cov --cov-report term-missing --cov isotopic_logging tests/
after_success:
  - codecov
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false
  slack:
    secure: UfWX4iCYnr7ompWCcZnR8wlU1t3GXuQHoa1j3Cw8K4BozN1Hbga30ExO+wvxzGESjZsWgjVKLbq5hXiTedtRnh5L8/ncmV8pCrXawBitgEJrk+pwFyyXGsNO39JS16sKj+47PAV4hvDL+Adnx16uEUvnpEfVfD+ecxYBK8Wfl+o=
