language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install -r .test-requirements-2.6.txt; fi
  - pip install -r .test-requirements.txt
  - pip install -e . --use-mirrors
script:
  - behave --no-capture
  - nosetests --with-coverage --cover-erase --nocapture
after_success:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false
